package com.nis1.thesis.sdk;

/**
 * Data payload for host-based security alert events.
 * <p>
 * This class represents security alerts generated by host-based detection systems
 * such as HIDS (Host Intrusion Detection Systems), antivirus software, or other
 * endpoint security tools. It contains essential information about security incidents
 * affecting individual hosts.
 * </p>
 * <p>
 * Host alerts typically include information about the source of the threat,
 * a description of the detected activity, and the severity level for prioritization.
 * </p>
 *
 * @author NIS1
 * @version 1.0
 * @since September 10, 2025
 */
public class HostAlertData {
    private String sourceIp;
    private String description;
    private String severity;

    /**
     * Default constructor for JSON deserialization.
     */
    public HostAlertData() {}

    /**
     * Constructs a new HostAlertData with the specified parameters.
     * 
     * @param sourceIp The IP address of the host where the alert originated
     * @param description A human-readable description of the security alert
     * @param severity The severity level of the alert (e.g., "LOW", "MEDIUM", "HIGH", "CRITICAL")
     */
    public HostAlertData(String sourceIp, String description, String severity) {
        this.sourceIp = sourceIp;
        this.description = description;
        this.severity = severity;
    }

    /**
     * Returns the IP address of the host where the alert originated.
     * 
     * @return The source IP address
     */
    public String getSourceIp() { return sourceIp; }
    
    /**
     * Sets the IP address of the host where the alert originated.
     * 
     * @param sourceIp The source IP address
     */
    public void setSourceIp(String sourceIp) { this.sourceIp = sourceIp; }

    /**
     * Returns a human-readable description of the security alert.
     * 
     * @return The alert description
     */
    public String getDescription() { return description; }
    
    /**
     * Sets a human-readable description of the security alert.
     * 
     * @param description The alert description
     */
    public void setDescription(String description) { this.description = description; }

    /**
     * Returns the severity level of the alert.
     * 
     * @return The severity level (e.g., "LOW", "MEDIUM", "HIGH", "CRITICAL")
     */
    public String getSeverity() { return severity; }
    
    /**
     * Sets the severity level of the alert.
     * 
     * @param severity The severity level (e.g., "LOW", "MEDIUM", "HIGH", "CRITICAL")
     */
    public void setSeverity(String severity) { this.severity = severity; }
}
