package com.nis1.thesis.sdk;

/**
 * Data payload for Network Intrusion Detection System (NIDS) alerts.
 * <p>
 * This class represents security alerts generated by network-based intrusion detection
 * systems such as Suricata, Snort, or other NIDS technologies. It contains detailed
 * information about network traffic patterns that have triggered security signatures.
 * </p>
 * <p>
 * NIDS alerts typically include source and destination network information,
 * protocol details, and signature information that can be used for threat analysis
 * and automated response actions.
 * </p>
 *
 * @author NIS1
 * @version 1.0
 * @since September 10, 2025
 */
public class NidsAlertData {
    private String sourceIp;
    private String destinationIp;
    private Integer sourcePort;
    private Integer destinationPort;
    private String protocol;
    private String signature;
    private String signatureSeverity;
    private String category;
    private String hostTag;

    /**
     * Default constructor for JSON deserialization.
     */
    public NidsAlertData() {}

    /**
     * Constructs a NIDS alert with basic network and signature information.
     * 
     * @param sourceIp The source IP address of the network traffic
     * @param destinationIp The destination IP address of the network traffic
     * @param signature The detection signature or rule that triggered the alert
     * @param signatureSeverity The severity level of the signature (e.g., "1", "2", "3" where 1 is highest)
     */
    public NidsAlertData(String sourceIp, String destinationIp, String signature, String signatureSeverity) {
        this.sourceIp = sourceIp;
        this.destinationIp = destinationIp;
        this.signature = signature;
        this.signatureSeverity = signatureSeverity;
    }

    /**
     * Returns the source IP address of the network traffic.
     * 
     * @return The source IP address
     */
    public String getSourceIp() { return sourceIp; }
    
    /**
     * Sets the source IP address of the network traffic.
     * 
     * @param sourceIp The source IP address
     */
    public void setSourceIp(String sourceIp) { this.sourceIp = sourceIp; }

    /**
     * Returns the destination IP address of the network traffic.
     * 
     * @return The destination IP address
     */
    public String getDestinationIp() { return destinationIp; }
    
    /**
     * Sets the destination IP address of the network traffic.
     * 
     * @param destinationIp The destination IP address
     */
    public void setDestinationIp(String destinationIp) { this.destinationIp = destinationIp; }

    /**
     * Returns the source port number of the network traffic.
     * 
     * @return The source port number, or null if not applicable
     */
    public Integer getSourcePort() { return sourcePort; }
    
    /**
     * Sets the source port number of the network traffic.
     * 
     * @param sourcePort The source port number
     */
    public void setSourcePort(Integer sourcePort) { this.sourcePort = sourcePort; }

    /**
     * Returns the destination port number of the network traffic.
     * 
     * @return The destination port number, or null if not applicable
     */
    public Integer getDestinationPort() { return destinationPort; }
    
    /**
     * Sets the destination port number of the network traffic.
     * 
     * @param destinationPort The destination port number
     */
    public void setDestinationPort(Integer destinationPort) { this.destinationPort = destinationPort; }

    /**
     * Returns the protocol used in the network traffic.
     * 
     * @return The protocol (e.g., "TCP", "UDP", "ICMP")
     */
    public String getProtocol() { return protocol; }
    
    /**
     * Sets the protocol used in the network traffic.
     * 
     * @param protocol The protocol (e.g., "TCP", "UDP", "ICMP")
     */
    public void setProtocol(String protocol) { this.protocol = protocol; }

    /**
     * Returns the detection signature or rule that triggered this alert.
     * 
     * @return The signature description
     */
    public String getSignature() { return signature; }
    
    /**
     * Sets the detection signature or rule that triggered this alert.
     * 
     * @param signature The signature description
     */
    public void setSignature(String signature) { this.signature = signature; }

    /**
     * Returns the severity level of the signature that triggered this alert.
     * 
     * @return The severity level (e.g., "1", "2", "3" where 1 is highest)
     */
    public String getSignatureSeverity() { return signatureSeverity; }
    
    /**
     * Sets the severity level of the signature that triggered this alert.
     * 
     * @param signatureSeverity The severity level (e.g., "1", "2", "3" where 1 is highest)
     */
    public void setSignatureSeverity(String signatureSeverity) { this.signatureSeverity = signatureSeverity; }

    /**
     * Returns the threat category classification for this alert.
     * 
     * @return The category (e.g., "Trojan", "Policy Violation", "Attempted Administrator Privilege Gain")
     */
    public String getCategory() { return category; }
    
    /**
     * Sets the threat category classification for this alert.
     * 
     * @param category The category (e.g., "Trojan", "Policy Violation", "Attempted Administrator Privilege Gain")
     */
    public void setCategory(String category) { this.category = category; }

    /**
     * Returns the host tag or label associated with this alert.
     * 
     * @return The host tag for organizational or filtering purposes
     */
    public String getHostTag() { return hostTag; }
    
    /**
     * Sets the host tag or label associated with this alert.
     * 
     * @param hostTag The host tag for organizational or filtering purposes
     */
    public void setHostTag(String hostTag) { this.hostTag = hostTag; }
}