package com.nis1.thesis.udm;

/**
 * SuricataAlertData - Comprehensive payload for Suricata NIDS alerts
 * 
 * This class represents detailed security alerts generated by Suricata Network
 * Intrusion Detection System. It contains all relevant network traffic information,
 * signature details, threat classification, and scoring metrics.
 * 
 * Used by SuricataModule to publish standardized alerts.network.suricata events
 * to the SOAR framework via the ModuleRegistry.
 */
public class SuricataAlertData {
    
    // Alert identification
    private String alertId;
    private String signatureId;
    private String signature;
    
    // Network information
    private String sourceIp;
    private String destinationIp;
    private Integer sourcePort;
    private Integer destinationPort;
    private String protocol;
    
    // Classification
    private String severity;           // critical, high, medium, low
    private String category;           // malware, exploit, reconnaissance, etc.
    private String alertType;          // Same as category for consistency
    
    // Threat scoring
    private Integer threatScore;       // 0-100
    private Integer confidenceScore;   // 0-100
    
    // Optional Suricata-specific metadata
    private String action;             // allowed, blocked, etc.
    private String flowId;
    private Long packetCount;
    private Long byteCount;
    
    /**
     * Default constructor for JSON deserialization
     */
    public SuricataAlertData() {}
    
    /**
     * Constructor with essential fields
     */
    public SuricataAlertData(String alertId, String signatureId, String signature,
                           String sourceIp, String destinationIp, String severity) {
        this.alertId = alertId;
        this.signatureId = signatureId;
        this.signature = signature;
        this.sourceIp = sourceIp;
        this.destinationIp = destinationIp;
        this.severity = severity;
    }
    
    // Getters and Setters
    
    public String getAlertId() { return alertId; }
    public void setAlertId(String alertId) { this.alertId = alertId; }
    
    public String getSignatureId() { return signatureId; }
    public void setSignatureId(String signatureId) { this.signatureId = signatureId; }
    
    public String getSignature() { return signature; }
    public void setSignature(String signature) { this.signature = signature; }
    
    public String getSourceIp() { return sourceIp; }
    public void setSourceIp(String sourceIp) { this.sourceIp = sourceIp; }
    
    public String getDestinationIp() { return destinationIp; }
    public void setDestinationIp(String destinationIp) { this.destinationIp = destinationIp; }
    
    public Integer getSourcePort() { return sourcePort; }
    public void setSourcePort(Integer sourcePort) { this.sourcePort = sourcePort; }
    
    public Integer getDestinationPort() { return destinationPort; }
    public void setDestinationPort(Integer destinationPort) { this.destinationPort = destinationPort; }
    
    public String getProtocol() { return protocol; }
    public void setProtocol(String protocol) { this.protocol = protocol; }
    
    public String getSeverity() { return severity; }
    public void setSeverity(String severity) { this.severity = severity; }
    
    public String getCategory() { return category; }
    public void setCategory(String category) { this.category = category; }
    
    public String getAlertType() { return alertType; }
    public void setAlertType(String alertType) { this.alertType = alertType; }
    
    public Integer getThreatScore() { return threatScore; }
    public void setThreatScore(Integer threatScore) { this.threatScore = threatScore; }
    
    public Integer getConfidenceScore() { return confidenceScore; }
    public void setConfidenceScore(Integer confidenceScore) { this.confidenceScore = confidenceScore; }
    
    public String getAction() { return action; }
    public void setAction(String action) { this.action = action; }
    
    public String getFlowId() { return flowId; }
    public void setFlowId(String flowId) { this.flowId = flowId; }
    
    public Long getPacketCount() { return packetCount; }
    public void setPacketCount(Long packetCount) { this.packetCount = packetCount; }
    
    public Long getByteCount() { return byteCount; }
    public void setByteCount(Long byteCount) { this.byteCount = byteCount; }
    
    @Override
    public String toString() {
        return "SuricataAlertData{" +
                "alertId='" + alertId + '\'' +
                ", signature='" + signature + '\'' +
                ", severity='" + severity + '\'' +
                ", sourceIp='" + sourceIp + '\'' +
                ", destinationIp='" + destinationIp + '\'' +
                ", protocol='" + protocol + '\'' +
                ", threatScore=" + threatScore +
                '}';
    }
}
