package com.nis1.thesis.udm;

import com.google.gson.annotations.SerializedName;

/**
 * ZeekAlertData - Comprehensive payload for Zeek NSM notices
 * 
 * This class represents security alerts generated by Zeek Network Security
 * Monitor.
 * It contains network traffic information, notice details, threat
 * classification,
 * and scoring metrics.
 * 
 * Used by ZeekHttpModule to publish standardized alerts.network.zeek events
 * to the SOAR framework via the ModuleRegistry.
 */
public class ZeekAlertData {

    // Alert identification
    @SerializedName("alert_id")
    private String alertId;
    @SerializedName("note_type")
    private String noteType; // Zeek notice type (e.g., Scan::Port_Scan)
    @SerializedName("signature")
    private String signature; // Notice message
    @SerializedName("sub_message")
    private String subMessage; // Additional notice details

    // Network information
    @SerializedName("source_ip")
    private String sourceIp;
    @SerializedName("destination_ip")
    private String destinationIp;
    @SerializedName("source_port")
    private Integer sourcePort;
    @SerializedName("destination_port")
    private Integer destinationPort;
    @SerializedName("protocol")
    private String protocol;

    // Classification
    @SerializedName("severity")
    private String severity; // critical, high, medium, low
    @SerializedName("category")
    private String category; // ransomware, malware, reconnaissance, etc.
    @SerializedName("alert_type")
    private String alertType; // Same as category for consistency

    // Threat scoring
    @SerializedName("threat_score")
    private Integer threatScore; // 0-100
    @SerializedName("confidence_score")
    private Integer confidenceScore; // 0-100

    // Optional Zeek-specific metadata
    @SerializedName("uid")
    private String uid; // Zeek connection UID
    @SerializedName("zeek_timestamp")
    private String zeekTimestamp; // Original Zeek timestamp
    @SerializedName("actions")
    private String actions; // Actions taken by Zeek

    /**
     * Default constructor for JSON deserialization
     */
    public ZeekAlertData() {
    }

    /**
     * Constructor with essential fields
     */
    public ZeekAlertData(String alertId, String noteType, String signature,
            String sourceIp, String severity) {
        this.alertId = alertId;
        this.noteType = noteType;
        this.signature = signature;
        this.sourceIp = sourceIp;
        this.severity = severity;
    }

    // Getters and Setters

    public String getAlertId() {
        return alertId;
    }

    public void setAlertId(String alertId) {
        this.alertId = alertId;
    }

    public String getNoteType() {
        return noteType;
    }

    public void setNoteType(String noteType) {
        this.noteType = noteType;
    }

    public String getSignature() {
        return signature;
    }

    public void setSignature(String signature) {
        this.signature = signature;
    }

    public String getSubMessage() {
        return subMessage;
    }

    public void setSubMessage(String subMessage) {
        this.subMessage = subMessage;
    }

    public String getSourceIp() {
        return sourceIp;
    }

    public void setSourceIp(String sourceIp) {
        this.sourceIp = sourceIp;
    }

    public String getDestinationIp() {
        return destinationIp;
    }

    public void setDestinationIp(String destinationIp) {
        this.destinationIp = destinationIp;
    }

    public Integer getSourcePort() {
        return sourcePort;
    }

    public void setSourcePort(Integer sourcePort) {
        this.sourcePort = sourcePort;
    }

    public Integer getDestinationPort() {
        return destinationPort;
    }

    public void setDestinationPort(Integer destinationPort) {
        this.destinationPort = destinationPort;
    }

    public String getProtocol() {
        return protocol;
    }

    public void setProtocol(String protocol) {
        this.protocol = protocol;
    }

    public String getSeverity() {
        return severity;
    }

    public void setSeverity(String severity) {
        this.severity = severity;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public String getAlertType() {
        return alertType;
    }

    public void setAlertType(String alertType) {
        this.alertType = alertType;
    }

    public Integer getThreatScore() {
        return threatScore;
    }

    public void setThreatScore(Integer threatScore) {
        this.threatScore = threatScore;
    }

    public Integer getConfidenceScore() {
        return confidenceScore;
    }

    public void setConfidenceScore(Integer confidenceScore) {
        this.confidenceScore = confidenceScore;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    public String getZeekTimestamp() {
        return zeekTimestamp;
    }

    public void setZeekTimestamp(String zeekTimestamp) {
        this.zeekTimestamp = zeekTimestamp;
    }

    public String getActions() {
        return actions;
    }

    public void setActions(String actions) {
        this.actions = actions;
    }

    @Override
    public String toString() {
        return "ZeekAlertData{" +
                "alertId='" + alertId + '\'' +
                ", noteType='" + noteType + '\'' +
                ", signature='" + signature + '\'' +
                ", severity='" + severity + '\'' +
                ", sourceIp='" + sourceIp + '\'' +
                ", destinationIp='" + destinationIp + '\'' +
                ", protocol='" + protocol + '\'' +
                ", threatScore=" + threatScore +
                '}';
    }
}
