package com.nis1.thesis.udm;

/**
 * ZeekAlertData - Payload for Zeek NIDS alerts
 * 
 * Represents security events generated by Zeek (formerly Bro).
 * Normalizes Zeek log data into a format compatible with the SOAR SDK.
 */
public class ZeekAlertData {

    // Alert identification
    private String alertId; // System generated ID
    private String uid; // Zeek connection UID
    private String noticeType; // e.g., "Scan::Port_Scan"
    private String msg; // Alert description
    private String subMsg; // Additional detail

    // Network information
    private String sourceIp; // id.orig_h
    private String destinationIp; // id.resp_h
    private Integer sourcePort; // id.orig_p
    private Integer destinationPort; // id.resp_p
    private String protocol; // proto

    // Classification
    private String severity; // critical, high, medium, low
    private String category; // inferred category

    // Threat scoring
    private Integer threatScore; // 0-100
    private Integer confidenceScore; // 0-100

    // Optional Zeek-specific metadata
    private String peerDescr;
    private String actions;
    private Double suppressFor;

    public ZeekAlertData() {
    }

    // Getters and Setters

    public String getAlertId() {
        return alertId;
    }

    public void setAlertId(String alertId) {
        this.alertId = alertId;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    public String getNoticeType() {
        return noticeType;
    }

    public void setNoticeType(String noticeType) {
        this.noticeType = noticeType;
    }

    public String getMsg() {
        return msg;
    }

    public void setMsg(String msg) {
        this.msg = msg;
    }

    public String getSubMsg() {
        return subMsg;
    }

    public void setSubMsg(String subMsg) {
        this.subMsg = subMsg;
    }

    public String getSourceIp() {
        return sourceIp;
    }

    public void setSourceIp(String sourceIp) {
        this.sourceIp = sourceIp;
    }

    public String getDestinationIp() {
        return destinationIp;
    }

    public void setDestinationIp(String destinationIp) {
        this.destinationIp = destinationIp;
    }

    public Integer getSourcePort() {
        return sourcePort;
    }

    public void setSourcePort(Integer sourcePort) {
        this.sourcePort = sourcePort;
    }

    public Integer getDestinationPort() {
        return destinationPort;
    }

    public void setDestinationPort(Integer destinationPort) {
        this.destinationPort = destinationPort;
    }

    public String getProtocol() {
        return protocol;
    }

    public void setProtocol(String protocol) {
        this.protocol = protocol;
    }

    public String getSeverity() {
        return severity;
    }

    public void setSeverity(String severity) {
        this.severity = severity;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public Integer getThreatScore() {
        return threatScore;
    }

    public void setThreatScore(Integer threatScore) {
        this.threatScore = threatScore;
    }

    public Integer getConfidenceScore() {
        return confidenceScore;
    }

    public void setConfidenceScore(Integer confidenceScore) {
        this.confidenceScore = confidenceScore;
    }

    public String getPeerDescr() {
        return peerDescr;
    }

    public void setPeerDescr(String peerDescr) {
        this.peerDescr = peerDescr;
    }

    public String getActions() {
        return actions;
    }

    public void setActions(String actions) {
        this.actions = actions;
    }

    public Double getSuppressFor() {
        return suppressFor;
    }

    public void setSuppressFor(Double suppressFor) {
        this.suppressFor = suppressFor;
    }

    @Override
    public String toString() {
        return "ZeekAlertData{" +
                "uid='" + uid + '\'' +
                ", noticeType='" + noticeType + '\'' +
                ", src='" + sourceIp + '\'' +
                ", dst='" + destinationIp + '\'' +
                ", severity='" + severity + '\'' +
                '}';
    }
}
